# defines MFCC configuration, following Kaldi's conventions
MFCC:
    config_path: ../configs/mfcc.conf
    apply_cmvn_sliding: False
    norm_vars: False
    center: True
    cmn_window: 300

# defines properties of x-vector extractor, such as neural net, ...
EmbeddingExtractor:
    onnx_path: ../models/final.onnx

# specifies possible transformations to embeddings - mean subtraction, LDA, l2 normalization, ...
Transforms:
    mean: ../models/mean.npy
    lda: ../models/LDA.npy
    use_l2_norm: True
