MFCC:
    config_path: ../configs/mfcc.conf
    apply_cmvn_sliding: False
    norm_vars: False
    center: True
    cmn_window: 300

EmbeddingExtractor:
    nnet: ../models/x-vectors/0003_sre16_v2_1a/exp/xvector_nnet_1a/final.raw
    use_gpu: False
    min_chunk_size: 25
    chunk_size: 10000
    cache_capacity: 64